apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: supervision
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: LISTEN
              value: "45876"
            - name: HUB_URL
              value: "http://beszel.supervision.svc.cluster.local:8090"
          envFrom:
            - secretRef:
                name: beszel-agent-key
            - secretRef:
                name: beszel-agent-token
          image: henrygd/beszel-agent:0.14.1
          imagePullPolicy: Always
          name: beszel-agent
          ports:
            - containerPort: 45876
              hostPort: 45876
      restartPolicy: Always
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
