apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k3s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    apps:
      - name: tandoor
        image: vabene1111/recipes:2.3.5
        env:
          - name: TZ
            value: Europe/Paris
          - name: DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: tandoor-database-app
                key: host
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: tandoor-database-app
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tandoor-database-app
                key: password
          - name: DB_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: tandoor-database-app
                key: dbname
        volumeMounts:
          - name: tandoor-staticfiles
            mountPath: /opt/recipes/staticfiles
          - name: tandoor-mediafiles
            mountPath: /opt/recipes/mediafiles
        volumes:
          - name: tandoor-staticfiles
            persistentVolumeClaim:
              claimName: tandoor-staticfiles
          - name: tandoor-mediafiles
            persistentVolumeClaim:
              claimName: tandoor-mediafiles
        service: 8080
        ingress:
          domain: tandoor.home
        pvc:
          - tandoor-staticfiles
          - tandoor-mediafiles
