apiVersion: v1
data:
  SECRET_KEY: ENC[AES256_GCM,data:30N4Q2F+bysFUasr4FznNndZGSPwOP0eR6S1ikAIXhNqM3YXgC3KJIge6qSZ8HX4+TiOSBFMMnsBYCEED96kERjxrS8=,iv:A2YeKxpnP38MWTBKL4xGmyjuXQzxtNr/QeHKM5Va//k=,tag:WQqbMrimlzgwUQU5C0mEgw==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: tandoor-secret-key
  namespace: tandoor
sops:
  age:
    - recipient: age13c2xt7plpv0g6y9qcazat02w9l35wcadv8xzqntpr4x3c80u0cjqggarnh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWFZUUndXVWVuWVpKaWtT
        S09yZmx1R1BMUE5ZUENobE1RMmdlM1JOa2t3ClhCNmludUx6bXJra1pxbGpySkZJ
        eFAwS2tBak1MNXRpNEtyRlR5MTFwb0UKLS0tIGpOVzdBekZaZmUrNCtNV3VCOUFk
        WE1zWEFHWmFCMHJFRm44VUt3T0RwNWMK7v//X+hvQ2JLBl+KKfSL4ckMVDonpUE7
        GafyDKNgiTQ+eNyIvuo9pPPbMYVwfII+eCqGtWlV3sNUWDS0jMpjIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T23:22:38Z"
  mac: ENC[AES256_GCM,data:zGGuO7OLr9xLJ/35jL8qp7XbrWP0Q5XmGadtoAtJSOsYIkLGVmosPYeBGymrPLXc4NkK2WLvuEktbFSfku9qO+IojWjRxo7rK7K2XM+r5TsUou/0safVEEIS+yhz1zrbc5eDhghPEORAOsfuvvwFpIDdP/qoprj8MwYjKdnCCaA=,iv:QJc3H+cD/bbA1Y32g5lkpzfissI60Hz/VAgD/gtfQog=,tag:EwzyVFKWxT7mOFA8ZyqC1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
