---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
spec:
  interval: 15m
  url: https://pkgs.tailscale.com/helmcharts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.90.6
      sourceRef:
        kind: HelmRepository
        name: tailscale
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth
      valuesKey: clientId
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-oauth
      valuesKey: clientSecret
      targetPath: oauth.clientSecret
