apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisper
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k3s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    apps:
      - name: whisper
        image: rhasspy/wyoming-whisper:3.7.0@sha256:ea74afa3e3c347cd031d946b4950b7438ae4bfd07ef96a04ac8a7095f36f4ac6
        env:
          - name: TZ
            value: Europe/Paris
        args:
          - "--model"
          - "medium"
          - "--language"
          - "fr"
        volumeMounts:
          - name: whisper-data
            mountPath: /data
        volumes:
          - name: whisper-data
            persistentVolumeClaim:
              claimName: whisper-data
        service: 10300
        ingress:
          domain: whisper.lan
        pvc:
          - whisper-data
