---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: jellyfin
  path: ./k3s/apps/jellyfin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: navidrome
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: navidrome
  path: ./k3s/apps/navidrome
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: home-assistant
  path: ./k3s/apps/home-assistant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: immich
  path: ./k3s/apps/immich
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
