---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: jellyfin
  path: ./k3s/infra/jellyfin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

