apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k3s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    apps:
      - name: navidrome
        image: deluan/navidrome:0.58.0
        env:
          - name: ND_PROMETHEUS_ENABLED
            value: "true"
          - name: ND_PLUGINS_ENABLED
            value: "true"
          - name: ND_PLUGINS_FOLDER
            value: /plugin
          - name: ND_ENABLETRANSCODINGCONFIG
            value: "true"
        volumeMounts:
          - name: navidrome-data
            mountPath: /data
          - name: navidrome-music
            mountPath: /music
          - name: navidrome-plugin
            mountPath: /plugin
        volumes:
          - name: navidrome-data
            persistentVolumeClaim:
              claimName: navidrome-data
          - name: navidrome-music
            persistentVolumeClaim:
              claimName: navidrome-music
          - name: navidrome-plugin
            persistentVolumeClaim:
              claimName: navidrome-plugin
        service: 4533
        ingress:
          domain: navidrome.home
        pvc:
          - navidrome-data
          - navidrome-music
          - navidrome-plugin
