apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k3s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    apps:
      - name: jellyfin
        image: jellyfin/jellyfin:10.11.1@sha256:c7dd335d455c95ad3fe7550824d93ceb911914bf4210e7899e11f9611ae53a92
        env:
          - name: JELLYFIN_CONFIG_DIR
            value: /config
          - name: JELLYFIN_DATA_DIR
            value: /data
          - name: JELLYFIN_CACHE_DIR
            value: /cache
          - name: TZ
            value: Europe/Paris
        volumeMounts:
          - name: jellyfin-config
            mountPath: /config
          - name: jellyfin-data
            mountPath: /data
          - name: jellyfin-cache
            mountPath: /cache
          - name: jellyfin-media
            mountPath: /media
        volumes:
          - name: jellyfin-config
            persistentVolumeClaim:
              claimName: jellyfin-config
          - name: jellyfin-data
            persistentVolumeClaim:
              claimName: jellyfin-data
          - name: jellyfin-cache
            persistentVolumeClaim:
              claimName: jellyfin-cache
          - name: jellyfin-media
            persistentVolumeClaim:
              claimName: jellyfin-media
        service: 8096
        ingress:
          domain: jellyfin.home
        pvc:
          - jellyfin-config
          - jellyfin-data
          - jellyfin-cache
          - jellyfin-media
