apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    homeassistant:
      external_url: "http://home-assistant.home"
      internal_url: "http://home-assistant.home"

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
