---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: trek
spec:
  interval: 15m
  url: https://liketrek.github.io/TREK

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trek
spec:
  interval: 10m
  chart:
    spec:
      chart: trek
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: trek
  values:
    env:
      TZ: "Europe/Paris"
      DEFAULT_LANGUAGE: "fr"
      APP_URL: "http://trek.lan"

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: trek.lan
          paths:
            - /
