apiVersion: v1
kind: PersistentVolume
metadata:
  name: trek-local-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  claimRef:
    namespace: trek
    name: trek-local-data
  hostPath:
    path: /home/homekube/trek/data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-local-data
  namespace: trek
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path