apiVersion: v1
data:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:PZWeCjV1cZlNakwRWZWv6xyjjh1GHrIjCqOBEVZ1GpjdJdqgeyVsITOtgY2ChOeGeaJk3/Kv2qRllbvrRdl+1nqJG9NBHJ0Fh8Uh3RAQjPV7B2tpWB8IvQ==,iv:NQoloKLsjZWdB/LwU7vz5V2G3tXqjDgzy1RNWkMGA3g=,tag:2TEkezDf3KtwSE5gMGjctg==,type:str]
  ADMIN_EMAIL: ENC[AES256_GCM,data:bq8S38Qf1cVcx6hxhz5IRF3XiwSTu3Sp,iv:iO+u6XlBCvaSfW4uWV9Pk48kuEJQOn0Q7SX2UIET2mM=,tag:vG1TIiQPW8GlrBDyTKqIHg==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:jQLwb+QJUdR59Ev5WFVfN8iZene356e6,iv:n8ic2lwT6fnF6NANjjJ3fAgd5KSnm72hBms1bGP5Nv0=,tag:LQarpIYjm5zY8/Dbb5DC4A==,type:str]
kind: Secret
metadata:
  name: trek-secrets
  namespace: trek
type: Opaque
sops:
  age:
    - recipient: age13c2xt7plpv0g6y9qcazat02w9l35wcadv8xzqntpr4x3c80u0cjqggarnh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRFRFN3lEai9aUjdKK0k5
        NGF3blJEbUN0ZU1rUGxPSEJRYzFNTE5yUWdZCkZoc0MyTGZmSC9YNzR4cnNFTzlj
        MzRPSmE4dGxhVlEzbVh4bUtWTkNhL2sKLS0tIEdjZWFTMlRIck4zYmREak15K2s2
        MHhVdnVUWXdpUjNYSjQrSUtIRUVPY0UKIjt6ZFUussV5cJzfWsUpqZFyyWZFvHv2
        1ebgVU6ywtXeOS/KHofpJptHSptILqtdube6qOQUN8gi6rspTpXG2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-19T13:56:09Z"
  mac: ENC[AES256_GCM,data:L8CTnuRAMtobGeV9bpaowt+sg9PA9pfheszLZy2hu8N5o35CxuxbgWwP48QOyShL70kqspYY/hlBJCUgbGVkbmvOdIDlXAyeLfy0PJ8EXM8dvmUiTKGLl09W4fYq1f7mvFQy0fYcSVgpi+APpjxSg7IJf62yn99jYpLmETa76uI=,iv:Okm6DZaTqQz6oE+V+Oy9EzlqO7kf28hNX7Bca2Q5NMk=,tag:3+D2YJpv7jsLlSSEd+xxFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
