apiVersion: v1
data:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:4TwZN/yX74u0OaDPyqZajG+q/bpYurZUrhz/IuUHGR4vZ4OxN9XrO6mrliPGX+iahQ5AYnJMXAbR9cLZkLdfLqWjK9EIaMHdq2UJBkARuCHJVDup/WI4Ng==,iv:1QmWdNd2jLKaQxnFVKgoFazZFnudNx87p6P12NEncEE=,tag:kibpiAz7OwaC7Yy+GMtdmA==,type:str]
kind: Secret
metadata:
  name: trek-secrets
sops:
  age:
    - recipient: age13c2xt7plpv0g6y9qcazat02w9l35wcadv8xzqntpr4x3c80u0cjqggarnh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UXExWm1kb25TY1puOXhD
        WkxPRmQ4WTVlTWIxcG9HM09UTGZtRnM2Ym0wCnBDY0NDY1A3M1hpUUFiTGtVSWlO
        UnBrc3dHM3hhaU1Tc1pFV09lbTlmQnMKLS0tIGh3Zk5WWmEzT3QzbWUzdVlzanpL
        cVk4OThjNFY5bUZEMWNwOGZQQWJQZ3MK+m85M/u3P/zdcjLhjoC7R/gd+bRxNSDv
        YVjKh91xlzJg1iHCsye0M+aDCFQwXScDbseae899r6INaBWk/nywGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-19T13:29:36Z"
  mac: ENC[AES256_GCM,data:AkeOReaydYEW9j+FbrcqdmFcO80ebGT5buLt7jOnnmZEL2tkKSvGDkMuDYWUFg0qwGcLYTJAY/90L/jhsiS2J+lwuBlOhnNzFEARbAmjo3xLYlx4wVJewyk25c67hKuke+wZrMCPejgAgoFqNJuwzVVRC2y5L5msxUs4Z1E1MgQ=,iv:S4DzMp8VQ56Q8u16v3w+OseEhmder1iUiS+CcG2ckOw=,tag:ke48DAaOT5oZPtqRiRFz8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
