apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homer
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k3s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    apps:
      - name: homer
        image: b4bz/homer:v26.08.2@sha256:83e40d1b7c9d4be4b9b9081e7151543ceb081576301b33b38615ae3f1d6b3e92
        containerPort: 8080
        volumeMounts:
          - name: homer-config
            mountPath: /www/assets
        volumes:
          - name: homer-config
            configMap:
              name: homer-config
        service: 8080
        ingress:
          domain: home.lan
        env:
          - name: INIT_ASSETS
            value: "1"
          - name: TZ
            value: Europe/Paris
