---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs
spec:
  interval: 15m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs
spec:
  interval: 10m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: nfs
  valuesFrom:
    - kind: Secret
      name: nas
      valuesKey: server
      targetPath: nfs.server
    - kind: Secret
      name: nas
      valuesKey: path
      targetPath: nfs.path
  values:
    storageClass:
      name: nfs
      defaultClass: true
      pathPattern: "${namespace}/${pvcName}"
      reclaimPolicy: Retain
