---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
spec:
  interval: 15m
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: 0.10.3

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: immich
      version: 0.10.3
      sourceRef:
        kind: HelmRepository
        name: immich
  values:
    controllers:
      main:
        env:
          TZ: Europe/Paris
    immich:
      persistence:
        library:
          existingClaim: immich-library
    valkey:
      enabled: true
      persistence:
        data:
          storageClass: nfs
    server:
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.home
              paths:
                - path: "/"
                  service:
                    identifier: main
    machine-learning:
      persistence:
        cache:
          storageClass: nfs
