---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
spec:
  interval: 15m
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: 0.10.3

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: immich
  values:
    controllers:
      main:
        env:
          TZ: Europe/Paris
          DB_HOSTNAME:
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: host
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: user
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: password
          DB_DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: dbname
    immich:
      persistence:
        library:
          existingClaim: immich-library
    valkey:
      enabled: true
      persistence:
        data:
          storageClass: nfs
    server:
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.home
              paths:
                - path: "/"
                  service:
                    identifier: main
    machine-learning:
      persistence:
        cache:
          storageClass: nfs
