---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: kube-system
  path: ./k3s/infra/cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: nfs
  path: ./k3s/infra/nfs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: kube-system
  path: ./k3s/infra/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: tailscale
  path: ./k3s/infra/tailscale
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: supervision
  path: ./k3s/infra/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-notifications 
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: flux-system
  path: ./k3s/infra/flux-notifications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beszel
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: supervision
  path: ./k3s/infra/beszel
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: supervision
  path: ./k3s/infra/uptime-kuma
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kite
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: supervision
  path: ./k3s/infra/kite
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: supervision
  path: ./k3s/infra/cloudnative-pg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
