---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: kube-system
  path: ./k3s/infra/cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: nfs
  path: ./k3s/infra/nfs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: traefik
  path: ./k3s/infra/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
