apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: kube-system
  path: ./k3s/infra/cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
