apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: supervision
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: LISTEN
              value: "45876"
          envFrom:
            - secretRef:
                name: beszel-agent-key
          image: henrygd/beszel-agent:0.18.7@sha256:8874e2c53f9de5e063a6a80d6b617e20fa593ac5dc4eb4c6ce1f912f510f38f8
          imagePullPolicy: Always
          name: beszel-agent
          ports:
            - containerPort: 45876
              hostPort: 45876
          volumeMounts:
            - name: containerd-socket
              mountPath: /var/run/containerd/containerd.sock
              readOnly: true
      volumes:
        - name: containerd-socket
          hostPath: null
          path: /run/k3s/containerd/containerd.sock
          type: Socket
      restartPolicy: Always
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
