apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: supervision
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: LISTEN
              value: "45876"
          envFrom:
            - secretRef:
                name: beszel-agent-key
          image: henrygd/beszel-agent:0.16.1@sha256:dee59d68ac327a755aec7651dd31b9f9a6d7db3da6f093e16e8c36c1f71a18cd
          imagePullPolicy: Always
          name: beszel-agent
          ports:
            - containerPort: 45876
              hostPort: 45876
          volumeMounts:
            - name: containerd-socket
              mountPath: /var/run/containerd/containerd.sock
              readOnly: true
      volumes:
        - name: containerd-socket
          hostPath: null
          path: /run/k3s/containerd/containerd.sock
          type: Socket
      restartPolicy: Always
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
