apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k3s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    apps:
      - name: beszel
        image: henrygd/beszel:0.16.0@sha256:358d452b97e0e1714f0acab3442f753528c3ec006df513710315c9c96dff4b87
        volumeMounts:
          - name: beszel-data
            mountPath: /beszel_data
          - name: beszel-socket
            mountPath: /beszel_socket
        volumes:
          - name: beszel-data
            persistentVolumeClaim:
              claimName: beszel-data
          - name: beszel-socket
            persistentVolumeClaim:
              claimName: beszel-socket
        service: 8090
        ingress:
          domain: beszel.home
          annotations:
            traefik.ingress.kubernetes.io/proxy-read-timeout: "3600"
            traefik.ingress.kubernetes.io/proxy-send-timeout: "3600"
        pvc:
          - beszel-data
          - beszel-socket
