apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beszel
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k3s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    apps:
      - name: beszel
        image: henrygd/beszel:0.16.1@sha256:24c5513b364a2cb6f966819389128999817afbaebfe81ba2980289e39326f484
        volumeMounts:
          - name: beszel-data
            mountPath: /beszel_data
          - name: beszel-socket
            mountPath: /beszel_socket
        volumes:
          - name: beszel-data
            persistentVolumeClaim:
              claimName: beszel-data
          - name: beszel-socket
            persistentVolumeClaim:
              claimName: beszel-socket
        service: 8090
        ingress:
          domain: beszel.home
          annotations:
            traefik.ingress.kubernetes.io/proxy-read-timeout: "3600"
            traefik.ingress.kubernetes.io/proxy-send-timeout: "3600"
        pvc:
          - beszel-data
          - beszel-socket
