---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kite
spec:
  interval: 15m
  url: https://zxh326.github.io/kite

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kite
spec:
  interval: 10m
  chart:
    spec:
      chart: kite
      version: 0.7.2
      sourceRef:
        kind: HelmRepository
        name: kite
  values:
    ingress:
      enabled: true
      hosts:
        - host: kite.home
          paths:
          - path: /
            pathType: ImplementationSpecific
      className: traefik
    db:
      sqlite:
        persistence:
          pvc:
            enabled: true
            storageClass: nfs
