apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k3s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    apps:
      - name: adguard
        image: adguard/adguardhome:v0.107.70@sha256:33e2240c466b2bb1d4fe9d65fd86178160bf6ee8835cf7b50ab3a7c5e39571fe
        env:
          - name: TZ
            value: Europe/Paris
        volumeMounts:
          - name: adguard-work
            mountPath: /opt/adguardhome/work
          - name: /opt/adguardhome/conf
            mountPath: /opt/adguardhome/conf
        volumes:
          - name: adguard-work
            persistentVolumeClaim:
              claimName: adguard-work
          - name: adguard-conf
            persistentVolumeClaim:
              claimName: adguard-conf
        service: 53
        protocol: UDP 
        ingress:
          domain: adguard.home
        pvc:
          - adguard-work
          - adguard-conf
