apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k3s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    apps:
      - name: adguard
        image: adguard/adguardhome:v0.107.76@sha256:7157eb1dc3b26c7af1d6898759a7b3f7d0fa09891fbd2d3caa6abc1057a9179b
        env:
          - name: TZ
            value: Europe/Paris
        volumeMounts:
          - name: adguard-work
            mountPath: /opt/adguardhome/work
          - name: adguard-conf
            mountPath: /opt/adguardhome/conf
        volumes:
          - name: adguard-work
            persistentVolumeClaim:
              claimName: adguard-work
          - name: adguard-conf
            persistentVolumeClaim:
              claimName: adguard-conf
        service: 80
        ingress:
          domain: adguard.lan
        pvc:
          - adguard-work
          - adguard-conf
