{{- range .Values.apps }}
{{- if .ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  {{- if .ingress.annotations }}
  annotations:
    {{- toYaml .ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .name }}
            port:
              number: {{ .service }}
        path: /
        pathType: Prefix
{{- end }}
{{- end }}
