{{- range .Values.apps }}
{{- if .service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .service }}
      targetPort: {{ .service }}
      protocol: TCP
      name: {{ .service | quote }}
{{- end }}
{{- end }}
