---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg 
spec:
  interval: 15m
  url: https://cloudnative-pg.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.26.1
      sourceRef:
        kind: HelmRepository
        name: cnpg
  values:
    additionalEnv:
      - name: TZ
        value: Europe/Paris
